In [1]:
# 라이브러리 로드
import pandas as pd

C:\Users\EZEN\AppData\Local\Temp\ipykernel_48820\4202687922.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [4]:
# 1차원 데이터 : 스리즈 생성
# 데이터는 1차원 배열
# 인덱스는 기본값
value = [100,200,300,400]

pd_series1 = pd.Series(value) #class여서 대문자 S로 시작. 안에 내장된 함수가 있겠구나 ㅡ 바로 파악 가능.

#판다스에서는 print를 쓰지 않을 계획.

In [5]:
pd_series1 #변수명만 적어도 주피터 환경에서는 print 안 써도 다 보여줌. 안 쓸 때가 좀 더 보기가 좋음.

0    100
1    200
2    300
3    400
dtype: int64

In [6]:
print(pd_series1) #dtype의 의미는 데이터 유형은 숫자이며 64비트까지 지원해준다.라는 것.

0    100
1    200
2    300
3    400
dtype: int64


In [7]:
# index의 값을 지정하여 Series 생성
value = [5000,6000,6500,6500]
ser_index = ['아메리카노', '카페라떼', '카페모카', '카푸치노']

pd_series2 = pd.Series(value, index=ser_index)

print(pd_series2) # 이때 dtype은 index가 아니라 data value.. 매우 중요 포인트. 문자는 사칙연산이 안 되므로. +는 2개를 연결해주는 형태로 되지만, 나머지 연산은 불가.

아메리카노    5000
카페라떼     6000
카페모카     6500
카푸치노     6500
dtype: int64


In [8]:
# Series라는 Class에는 적어도 2개의 변수가 존재
# values, index 변수가 존재
print('Series의 value 값은', pd_series2.values)
print('Series의 index 값은', pd_series2.index)

#이러면 값이 배열로 보이게 됨.

Series의 value 값은 [5000 6000 6500 6500]
Series의 index 값은 Index(['아메리카노', '카페라떼', '카페모카', '카푸치노'], dtype='object')


In [9]:
print(type(pd_series2.values))
# 넘파이가 자동으로 이렇게 되는 거~

<class 'numpy.ndarray'>


In [12]:
# 2차원 데이터 형태 : DataFrame
value = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
df = pd.DataFrame(value)

In [13]:
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [14]:
df  #print를 안 쓰면 행렬을 정확하게 잡아준다. 칼럼별 라인 확인을 위해. 변수명만 썼을 때 보기가 더 좋아짐.

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [15]:
value = [
    [1,2,3],
    [4,5,6],
    [7,8,9]] 
_index = ['a','b','c'] #행의 개수 맞추기. 중복되지 않도록 유니크한 값을 index에 쓰는 게 좋음. (넘버링(순서), 시간 등)
_col = ['A','B','C'] #열의 개수 맞추기
df2 = pd.DataFrame(value, index=_index, columns=_col)
df2

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [16]:
# DataFrame이라는 Class에서는 적어도 3개의 변수가 존재
print(df2.values)
print(df2.index)
print(df2.columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Index(['a', 'b', 'c'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')


In [17]:
df.columns = ['가', '나', '다'] #이름 바꾸기

In [18]:
df2

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [19]:
# 딕셔너리 데이터 형태 : 사전형 데이터
# 리스트 데이터에서 index(위치) 대신에 key 값을 사용하는 형태
dict_1 = {
    "name" : 'kim',
    "age" : 20,
    'phone' : "01012345678"
}
print(dict_1)

{'name': 'kim', 'age': 20, 'phone': '01012345678'}


In [20]:
print(dict_1['name'])

kim


In [23]:
dict_1['name'] = ['kim', 'park']

In [22]:
dict_1

{'name': ['kim', 'park'], 'age': 20, 'phone': '01012345678'}

In [24]:
# 새로운 키 : 벨류 추가
# 매우 간단하게 추가할 수 있는 반면, 무분별하게 추가될 수도 있다는 점.
dict_1['address'] = 'Seoul'

In [25]:
dict_1

{'name': ['kim', 'park'],
 'age': 20,
 'phone': '01012345678',
 'address': 'Seoul'}

In [27]:
data = [
    {
        'id' : 'test',
        'password' : '1234'
    },
    {
        'id' : 'test2',
        'password' : '0000'
    }
]

#print(data(0.id)) #가장 사이드에 있는 것부터 차근차근 없애자. list에서 대괄호 추출할 땐 위치값 추출.
# 복합데이터에서 얘를 인식한다. key값들이 컬러배 값으로... 올라간다.... 

In [28]:
print(data)

[{'id': 'test', 'password': '1234'}, {'id': 'test2', 'password': '0000'}]


In [29]:
print(data[0]) #대괄호가 사라짐.

{'id': 'test', 'password': '1234'}


In [30]:
print(data[0]['id']) # 첫번째 위치에 있는 'id'의 값을 프린트해라.

test


In [31]:
df3 = pd.DataFrame(data)

In [32]:
df3

id password
0   test     1234
1  test2     0000

In [36]:
pd_dataframe_3 = pd.DataFrame(data)

print(pd_dataframe_3)

df3

      id password
0   test     1234
1  test2     0000


id password
0   test     1234
1  test2     0000